name: Genera Archivio Meteo Completo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # Esegue l'aggiornamento ogni 3 ore in automatico

permissions:
  contents: write

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests numpy matplotlib cartopy

    - name: Run weather generation script
      run: python genera_mappe.py

    - name: Commit and push generated maps
      run: |
        git config --global user.name 'actions-user'
        git config --global user.email 'actions@github.com'
        git add mappe_output/
        git commit -m "Aggiornamento automatico archivio mappe orarie ICON-2I [skip ci]" || exit 0
        git push
